language: objective-c
before_install:
  - cd `brew --repository` && brew update && git checkout bb7fcab && sed -i bak 's/111bf871bda84e72fdf93f2877d97591b918db2a/d1f9166ae0c7ef01ea16f950fbdfb195b587c857/' Library/Formula/v8.rb && brew install -f v8 && cd $TRAVIS_BUILD_DIR
  - sudo pip install paver
  - paver package_objc
script:
  - paver test_objc
notifications:
  slack:
    secure: Yeh8NM4tY3wE0nf813XXF1uK5L7bPr0owLmsN6cJqPvMpBQ1E83hwwsHTdzRWBkMreir6rT3vc3/1pac+gxtgDYmpYP0IfKYnFcCHISPjoxvXPaN3TcNSDnXMeRbO8V5dpAym3YMHODDg88J8lL0kJvxtg7mq7i4XKY1ue0yeVs=
